---
version: "2.1"


services:
  tick-collector:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
        - DOMAIN=stream-fxpractice.oanda.com
        #remember, never check-in your ACCESS_TOKEN or ACCOUNT_ID to SCM or share with anyone!
        - ACCESS_TOKEN=YOUR-TOKEN-HERE
        - ACCOUNT_ID=YOUR-ACCOUNT-ID-HERE
        - VERBOSE=0
        - MONGODB_NAME=instruments
        - MONGODB_HOST=mongodb-host-alias
        - MONGODB_PORT=27017
    links:
      - mongodb:mongodb-host-alias
  mongodb:
    restart: always
    image: mongo:3.4-jessie
    #if you want to persist data between restarts create local directory you want to mount
    # read more: https://docs.docker.com/engine/admin/volumes/volumes/
    #volumes:
    #  - "/local-dir-you-want-to-mount/mongodb:/data/db"
    ports:
      - "27018:27017"
